name: Metrics embed
on:
  schedule: [{cron: "0 * * * *"}]  # Runs hourly
  push: {branches: ["main"]}
  workflow_dispatch:              # Allows manual run from GitHub

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          base: header, activity, community, metadata
