name: Metrics
on:
  schedule:
    - cron: "0 */3 * * *"   # every 3 hours
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Metrics SVG
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, languages, activity, notable
          plugin_isocalendar: yes
          plugin_notable: yes
          plugin_languages: yes
          plugin_languages_ignored: html
          plugin_languages_skipped: lowlighter/metrics
          plugin_activity: yes
