name: Metrics
on:
  schedule:
    - cron: "0 16 * * *"   # daily at 16:00 UTC
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Metrics SVG
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: gist
          committer_gist: ${{ secrets.GIST }}
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, notable, projects, stargazers
          plugin_isocalendar: yes
          plugin_projects: yes
          plugin_stargazers: yes
          plugin_notable: yes
